name: matrix example
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [12,13,14]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.operating-system}}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NoodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build